# Generated by Django 5.2 on 2025-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
