# Generated by Django 5.2 on 2025-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_wechatuser_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='user_pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
