# Generated by Django 3.2.15 on 2025-05-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_wechatuser_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.wechatuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='moments.comment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.wechatuser')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='comments',
            field=models.ManyToManyField(related_name='commented_statuses', through='moments.Comment', to='moments.WeChatUser'),
        ),
        migrations.AddField(
            model_name='status',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_statuses', through='moments.Like', to='moments.WeChatUser'),
        ),
    ]
